# Generated by Django 2.1.7 on 2019-03-18 22:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ImageField(help_text='基金code', max_length=10, upload_to='')),
                ('name', models.CharField(blank=True, help_text='基金名称', max_length=30, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='FundDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateField()),
                ('data', models.FloatField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='UserFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('monitor', models.BooleanField(default=True)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.Fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
