# Generated by Django 2.1.7 on 2019-04-29 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='code',
            field=models.CharField(help_text='基金code', max_length=10),
        ),
        migrations.AlterField(
            model_name='funddetail',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fund.Fund'),
        ),
    ]
