# Generated by Django 2.1.7 on 2019-04-29 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20190429_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddetail',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.Fund'),
        ),
        migrations.AlterField(
            model_name='userfund',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fund.Fund'),
        ),
    ]
