# Generated by Django 2.1.7 on 2019-04-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20190430_1351'),
        ('fund', '0003_auto_20190429_2228'),
    ]

    operations = [
    ]
