# Generated by Django 2.1.7 on 2019-05-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_auto_20190501_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='code',
            field=models.CharField(help_text='基金code', max_length=10, unique=True),
        ),
    ]
